
FIRST_PERSON_SING = "mu"
SECOND_PERSON_SING = "gi"
THIRD_PERSON_SING = "ya"
FIRST_PERSON_PLU = "anyi"
SECOND_PERSON_PLU = "unu"
THIRD_PERSON_PLU = "ha"

ALL_PRONOUNS = [FIRST_PERSON_SING, SECOND_PERSON_SING, THIRD_PERSON_SING,
                FIRST_PERSON_PLU, SECOND_PERSON_PLU, THIRD_PERSON_PLU]

IMPERATIVE_PRONOUNS = [FIRST_PERSON_SING, THIRD_PERSON_SING, FIRST_PERSON_PLU,
                       THIRD_PERSON_PLU]
